remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Wannabe Batman]
logo: /assets/img/IMG_0879.png
description: [resume is somewhat fake, I will not be publishing my profile online.]







description: [do not use]
